# Imports

In [1]:
import pandas as pd
import numpy as np
import os

## repeated printouts
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## Read in data and make sure relevant columns are string/character 

- San Diego data: `naics_code` and `account_key`
- NAICS details data: `naics` (North American Industry Classification Systems)

Run code below; if pulling from github, pathname should be fine; if working elsewhere may need to edit path name at read in

In [3]:
# uncomment if u need to find your path: os.getcwd()
SD = sd_df = pd.read_csv("../public_data/sd_df.csv")
NA = naics_df = pd.read_csv("../public_data/naics_df.csv")

In [5]:
cols_sd_use = ["naics_code", "account_key"]
cols_naics_use = ["naics"]

sd_df[cols_sd_use] = sd_df[cols_sd_use].astype(str)
naics_df[cols_naics_use] = naics_df[cols_naics_use].astype(str)

sd_df.dtypes
naics_df.dtypes
sd_df.head()
naics_df.head()

account_key          object
dba_name             object
council_district     object
naics_code           object
naics_description    object
naics_nchar           int64
dtype: object

naics                object
naics_description    object
dtype: object

,account_key,dba_name,council_district,naics_code,naics_description,naics_nchar
0,1974000448,ERNST & YOUNG LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6
1,1974011093,HECHT SOLBERG ROBINSON GOLDBERG & BAGLEY LLP,cd_3,5411,LEGAL SERVICES,4
2,1978039819,RSM US LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6
3,1978042092,THORSNES BARTOLOTTA MCGUIRE LLP,cd_3,5411,LEGAL SERVICES,4
4,1979046817,KORENIC & WOJDOWSKI LLP,cd_7,5412,ACCOUNTING/TAX PREP/BOOKKEEP/PAYROLL SERVICES,4

    naics                 naics_description
0  111140                     Wheat Farming
1  111160                      Rice Farming
2  111150                      Corn Farming
3  111110                   Soybean Farming
4  111120  Oilseed (except Soybean) Farming

## "Inner join"- retain only San Diego businesses with details on their NAICS code

- Use the `naics_code` column in the San Diego business data as the join key
- Use the `naics` column in the NAICS code details data as the join key

- Do an inner join of the San Diego data onto the NAICS code details using these join keys
- After the inner join, print some examples of San Diego businesses lost in the merge
- Use value_counts() on the `naics_nchar` column in the San Diego data to see why they might have gotten lost

In [191]:
# your code here
inner_join = pd.merge(sd_df, naics_df, left_on='naics_code', right_on='naics', how='inner')
print(inner_join.shape)
inner_join 

# What's lost in the merge 
sd_df.naics_code.value_counts()
inner_join[inner_join.naics_code == 7222].shape

# Use value_counts() on the naics_nchar column in the San Diego data to see why they might have gotten lost
sd_df.naics_nchar.value_counts()
naics_df.naics.apply(lambda x: len(x)).value_counts()
inner_join.naics_nchar.value_counts()
# Only 6 nchar is preserved


print("##### Class answer:") 
newdf= sd_df.merge(naics_df, left_on = "naics_code", right_on = "naics", how = "inner")
newdf
lostrows = sd_df.merge(naics_df,left_on = "naics_code", right_on = "naics", indicator=True, how="outer")
lostrows[lostrows["_merge"] == "left_only"]
newdf.value_counts("naics_nchar")


print("##### Herbert answer:") 
#M = SD.merge()

(52, 11)

,account_key,dba_name,council_district,naics_code,naics_description_x,naics_nchar,new_naics_code,new_2_naics_code,new_second_naics_code,naics,naics_description_y
0,1974000448,ERNST & YOUNG LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
1,1978039819,RSM US LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
2,1982006408,MAX L. PERLATTI & ASSOCIATES LLP,cd_2,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
3,1984014611,RBTK LLP,cd_6,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
4,1985008871,CWGB&S CPAS,cd_3,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
5,1995006738,PADRES L P,cd_3,711211,SPORTS TEAMS AND CLUBS,6,711211,711211,711211,711211,Sports Teams and Clubs
6,1995007398,CRI 2000 LP,cd_3,321999,ALL OTHER MISCELLANEOUS WOOD PRODUCT MFG,6,321999,321999,321999,321999,All Other Miscellaneous Wood Product Manufactu...
7,1995007398,CRI 2000 LP,cd_3,321999,ALL OTHER MISCELLANEOUS WOOD PRODUCT MFG,6,321999,321999,321999,321999,All Other Miscellaneous Wood Product Manufactu...
8,1995007398,CRI 2000 LP,cd_3,321999,ALL OTHER MISCELLANEOUS WOOD PRODUCT MFG,6,321999,321999,321999,321999,All Other Miscellaneous Wood Product Manufactu...
9,1995007398,CRI 2000 LP,cd_3,321999,ALL OTHER MISCELLANEOUS WOOD PRODUCT MFG,6,321999,321999,321999,321999,All Other Miscellaneous Wood Product Manufactu...
10,1995007398,CRI 2000 LP,cd_3,321999,ALL OTHER MISCELLANEOUS WOOD PRODUCT MFG,6,321999,321999,321999,321999,All Other Miscellaneous Wood Product Manufactu...
11,1995007398,CRI 2000 LP,cd_3,321999,ALL OTHER MISCELLANEOUS WOOD PRODUCT MFG,6,321999,321999,321999,321999,All Other Miscellaneous Wood Product Manufactu...
12,1998004615,DELSEN & COMPANY LLP,cd_6,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
13,2000001077,MASSEY WEHR AND COMPANY LLP,cd_1,541213,TAX PREPARATION SERVICES,6,541213,541213,541213,541213,Tax Preparation Services
14,2003001470,GUM SAAN - THE LAND OF THE GOLDEN MOUNTAIN,cd_3,453998,ALL OTHER MISC STORE RETAILERS (EXC TOBACCO),6,453998,453998,453998,453998,All Other Miscellaneous Store Retailers (excep...
15,2003001470,GUM SAAN - THE LAND OF THE GOLDEN MOUNTAIN,cd_3,453998,ALL OTHER MISC STORE RETAILERS (EXC TOBACCO),6,453998,453998,453998,453998,All Other Miscellaneous Store Retailers (excep...
16,2003001470,GUM SAAN - THE LAND OF THE GOLDEN MOUNTAIN,cd_3,453998,ALL OTHER MISC STORE RETAILERS (EXC TOBACCO),6,453998,453998,453998,453998,All Other Miscellaneous Store Retailers (excep...
17,2003001470,GUM SAAN - THE LAND OF THE GOLDEN MOUNTAIN,cd_3,453998,ALL OTHER MISC STORE RETAILERS (EXC TOBACCO),6,453998,453998,453998,453998,All Other Miscellaneous Store Retailers (excep...
18,2004006421,ROBBINS GELLER RUDMAN & DOWD LLP,cd_3,541199,ALL OTHER LEGAL SERVICES,6,541199,541199,541199,541199,All Other Legal Services
19,2005012737,SLATER & TRUXAW LLP,cd_1,541199,ALL OTHER LEGAL SERVICES,6,541199,541199,541199,541199,All Other Legal Services
20,2006000166,GUERRERO JIMENEZ DIAZ & COMPANY LLP,cd_3,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
21,2006009239,CONNOR & CUNDEL LLP,cd_3,541199,ALL OTHER LEGAL SERVICES,6,541199,541199,541199,541199,All Other Legal Services
22,2006010738,WENTHUR LAW GROUP LLP,cd_2,541199,ALL OTHER LEGAL SERVICES,6,541199,541199,541199,541199,All Other Legal Services
23,2007000136,MOSS ADAMS LLP,cd_7,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
24,2007022822,THE LOAN COMPANY OF SAN DIEGO,cd_3,522291,CONSUMER LENDING,6,522291,522291,522291,522291,Consumer Lending
25,2008016718,BDO USA LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
26,2009003243,ALTMAN INVESTMENT COMPANY LP,cd_1,531312,NONRESIDENTIAL PROPERTY MANAGERS,6,531312,531312,531312,531312,Nonresidential Property Managers
27,2009010415,THE SUMMIT AT POINT LOMA APARTMENTS,cd_2,531311,RESIDENTIAL PROPERTY MANAGERS,6,531311,531311,531311,531311,Residential Property Managers
28,2010012365,LAPIZ PROPERTIES GROUP LTD,cd_1,531312,NONRESIDENTIAL PROPERTY MANAGERS,6,531312,531312,531312,531312,Nonresidential Property Managers
29,2010013586,SWENSON ADVISORS LLP,cd_3,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
30,2013053990,MURRILL & GERBINO LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
31,2013067165,ARIEL,cd_3,531311,RESIDENTIAL PROPERTY MANAGERS,6,531311,531311,531311,531311,Residential Property Managers
32,2014027828,STEES WALKER COMPANY LLP,cd_5,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
33,2014034430,ALVAREZ TAX & ACCOUNTING LLP,cd_6,541213,TAX PREPARATION SERVICES,6,541213,541213,541213,541213,Tax Preparation Services
34,2018000234,VINAS UNITED CRYPTO INVESTMENT GROUP,cd_6,523999,MISCELLANEOUS FINANCIAL INVESTMENT ACTIVITIES,6,523999,523999,523999,523999,Miscellaneous Financial Investment Activities
35,2018000234,VINAS UNITED CRYPTO INVESTMENT GROUP,cd_6,523999,MISCELLANEOUS FINANCIAL INVESTMENT ACTIVITIES,6,523999,523999,523999,523999,Miscellaneous Financial Investment Activities
36,2018023600,ALLIED UNIVERSAL SECURITY SERVICES,cd_5,561612,SECURITY GUARDS & PATROL SERVICES,6,561612,561612,561612,561612,Security Guards and Patrol Services
37,2019015278,BEYER BOULEVARD APARTMENTS LP,cd_8,531311,RESIDENTIAL PROPERTY MANAGERS,6,531311,531311,531311,531311,Residential Property Managers
38,2019023546,REIWA ACCOUNTING LLP,cd_3,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
39,2020007786,PRIMAL COFFEE COMPANY,cd_2,311999,ALL OTHER MISCELLANEOUS FOOD MFG,6,311999,311999,311999,311999,All Other Miscellaneous Food Manufacturing
40,2020007786,PRIMAL COFFEE COMPANY,cd_2,311999,ALL OTHER MISCELLANEOUS FOOD MFG,6,311999,311999,311999,311999,All Other Miscellaneous Food Manufacturing
41,2020007786,PRIMAL COFFEE COMPANY,cd_2,311999,ALL OTHER MISCELLANEOUS FOOD MFG,6,311999,311999,311999,311999,All Other Miscellaneous Food Manufacturing
42,2020007786,PRIMAL COFFEE COMPANY,cd_2,311999,ALL OTHER MISCELLANEOUS FOOD MFG,6,311999,311999,311999,311999,All Other Miscellaneous Food Manufacturing
43,2020007786,PRIMAL COFFEE COMPANY,cd_2,311999,ALL OTHER MISCELLANEOUS FOOD MFG,6,311999,311999,311999,311999,All Other Miscellaneous Food Manufacturing
44,2020013537,MOTHER TO MOTHER MIDWIFERY,cd_3,621399,OFFICES OF ALL OTH MISC HEALTH PRACTITIONERS,6,621399,621399,621399,621399,Offices of All Other Miscellaneous Health Prac...
45,2020013537,MOTHER TO MOTHER MIDWIFERY,cd_3,621399,OFFICES OF ALL OTH MISC HEALTH PRACTITIONERS,6,621399,621399,621399,621399,Offices of All Other Miscellaneous Health Prac...
46,2021010826,STARDUST FLOAT SPA LP,cd_2,812199,OTHER PERSONAL CARE SERVICES,6,812199,812199,812199,812199,Other Personal Care Services
47,2003021665,SDDR V LP,cd_7,523999,MISCELLANEOUS FINANCIAL INVESTMENT ACTIVITIES,6,523999,523999,523999,523999,Miscellaneous Financial Investment Activities
48,2003021665,SDDR V LP,cd_7,523999,MISCELLANEOUS FINANCIAL INVESTMENT ACTIVITIES,6,523999,523999,523999,523999,Miscellaneous Financial Investment Activities
49,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,811198,811198,811198,All Other Automotive Repair and Maintenance
50,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,811198,811198,811198,All Other Automotive Repair and Maintenance
51,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,811198,811198,811198,All Other Automotive Repair and Maintenance

naics_code
54111     47
5411      32
7222      14
541       13
541211    13
          ..
5621       1
53113      1
54199      1
44711      1
811198     1
Name: count, Length: 129, dtype: int64

(0, 11)

naics_nchar
5    150
4     89
6     49
3     42
2     23
Name: count, dtype: int64

naics
6    2270
Name: count, dtype: int64

naics_nchar
6    52
Name: count, dtype: int64

##### Class answer:

,account_key,dba_name,council_district,naics_code,naics_description_x,naics_nchar,new_naics_code,new_2_naics_code,new_second_naics_code,naics,naics_description_y
0,1974000448,ERNST & YOUNG LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
1,1978039819,RSM US LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
2,1982006408,MAX L. PERLATTI & ASSOCIATES LLP,cd_2,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
3,1984014611,RBTK LLP,cd_6,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
4,1985008871,CWGB&S CPAS,cd_3,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
5,1995006738,PADRES L P,cd_3,711211,SPORTS TEAMS AND CLUBS,6,711211,711211,711211,711211,Sports Teams and Clubs
6,1995007398,CRI 2000 LP,cd_3,321999,ALL OTHER MISCELLANEOUS WOOD PRODUCT MFG,6,321999,321999,321999,321999,All Other Miscellaneous Wood Product Manufactu...
7,1995007398,CRI 2000 LP,cd_3,321999,ALL OTHER MISCELLANEOUS WOOD PRODUCT MFG,6,321999,321999,321999,321999,All Other Miscellaneous Wood Product Manufactu...
8,1995007398,CRI 2000 LP,cd_3,321999,ALL OTHER MISCELLANEOUS WOOD PRODUCT MFG,6,321999,321999,321999,321999,All Other Miscellaneous Wood Product Manufactu...
9,1995007398,CRI 2000 LP,cd_3,321999,ALL OTHER MISCELLANEOUS WOOD PRODUCT MFG,6,321999,321999,321999,321999,All Other Miscellaneous Wood Product Manufactu...
10,1995007398,CRI 2000 LP,cd_3,321999,ALL OTHER MISCELLANEOUS WOOD PRODUCT MFG,6,321999,321999,321999,321999,All Other Miscellaneous Wood Product Manufactu...
11,1995007398,CRI 2000 LP,cd_3,321999,ALL OTHER MISCELLANEOUS WOOD PRODUCT MFG,6,321999,321999,321999,321999,All Other Miscellaneous Wood Product Manufactu...
12,1998004615,DELSEN & COMPANY LLP,cd_6,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
13,2000001077,MASSEY WEHR AND COMPANY LLP,cd_1,541213,TAX PREPARATION SERVICES,6,541213,541213,541213,541213,Tax Preparation Services
14,2003001470,GUM SAAN - THE LAND OF THE GOLDEN MOUNTAIN,cd_3,453998,ALL OTHER MISC STORE RETAILERS (EXC TOBACCO),6,453998,453998,453998,453998,All Other Miscellaneous Store Retailers (excep...
15,2003001470,GUM SAAN - THE LAND OF THE GOLDEN MOUNTAIN,cd_3,453998,ALL OTHER MISC STORE RETAILERS (EXC TOBACCO),6,453998,453998,453998,453998,All Other Miscellaneous Store Retailers (excep...
16,2003001470,GUM SAAN - THE LAND OF THE GOLDEN MOUNTAIN,cd_3,453998,ALL OTHER MISC STORE RETAILERS (EXC TOBACCO),6,453998,453998,453998,453998,All Other Miscellaneous Store Retailers (excep...
17,2003001470,GUM SAAN - THE LAND OF THE GOLDEN MOUNTAIN,cd_3,453998,ALL OTHER MISC STORE RETAILERS (EXC TOBACCO),6,453998,453998,453998,453998,All Other Miscellaneous Store Retailers (excep...
18,2004006421,ROBBINS GELLER RUDMAN & DOWD LLP,cd_3,541199,ALL OTHER LEGAL SERVICES,6,541199,541199,541199,541199,All Other Legal Services
19,2005012737,SLATER & TRUXAW LLP,cd_1,541199,ALL OTHER LEGAL SERVICES,6,541199,541199,541199,541199,All Other Legal Services
20,2006000166,GUERRERO JIMENEZ DIAZ & COMPANY LLP,cd_3,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
21,2006009239,CONNOR & CUNDEL LLP,cd_3,541199,ALL OTHER LEGAL SERVICES,6,541199,541199,541199,541199,All Other Legal Services
22,2006010738,WENTHUR LAW GROUP LLP,cd_2,541199,ALL OTHER LEGAL SERVICES,6,541199,541199,541199,541199,All Other Legal Services
23,2007000136,MOSS ADAMS LLP,cd_7,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
24,2007022822,THE LOAN COMPANY OF SAN DIEGO,cd_3,522291,CONSUMER LENDING,6,522291,522291,522291,522291,Consumer Lending
25,2008016718,BDO USA LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
26,2009003243,ALTMAN INVESTMENT COMPANY LP,cd_1,531312,NONRESIDENTIAL PROPERTY MANAGERS,6,531312,531312,531312,531312,Nonresidential Property Managers
27,2009010415,THE SUMMIT AT POINT LOMA APARTMENTS,cd_2,531311,RESIDENTIAL PROPERTY MANAGERS,6,531311,531311,531311,531311,Residential Property Managers
28,2010012365,LAPIZ PROPERTIES GROUP LTD,cd_1,531312,NONRESIDENTIAL PROPERTY MANAGERS,6,531312,531312,531312,531312,Nonresidential Property Managers
29,2010013586,SWENSON ADVISORS LLP,cd_3,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
30,2013053990,MURRILL & GERBINO LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
31,2013067165,ARIEL,cd_3,531311,RESIDENTIAL PROPERTY MANAGERS,6,531311,531311,531311,531311,Residential Property Managers
32,2014027828,STEES WALKER COMPANY LLP,cd_5,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
33,2014034430,ALVAREZ TAX & ACCOUNTING LLP,cd_6,541213,TAX PREPARATION SERVICES,6,541213,541213,541213,541213,Tax Preparation Services
34,2018000234,VINAS UNITED CRYPTO INVESTMENT GROUP,cd_6,523999,MISCELLANEOUS FINANCIAL INVESTMENT ACTIVITIES,6,523999,523999,523999,523999,Miscellaneous Financial Investment Activities
35,2018000234,VINAS UNITED CRYPTO INVESTMENT GROUP,cd_6,523999,MISCELLANEOUS FINANCIAL INVESTMENT ACTIVITIES,6,523999,523999,523999,523999,Miscellaneous Financial Investment Activities
36,2018023600,ALLIED UNIVERSAL SECURITY SERVICES,cd_5,561612,SECURITY GUARDS & PATROL SERVICES,6,561612,561612,561612,561612,Security Guards and Patrol Services
37,2019015278,BEYER BOULEVARD APARTMENTS LP,cd_8,531311,RESIDENTIAL PROPERTY MANAGERS,6,531311,531311,531311,531311,Residential Property Managers
38,2019023546,REIWA ACCOUNTING LLP,cd_3,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants
39,2020007786,PRIMAL COFFEE COMPANY,cd_2,311999,ALL OTHER MISCELLANEOUS FOOD MFG,6,311999,311999,311999,311999,All Other Miscellaneous Food Manufacturing
40,2020007786,PRIMAL COFFEE COMPANY,cd_2,311999,ALL OTHER MISCELLANEOUS FOOD MFG,6,311999,311999,311999,311999,All Other Miscellaneous Food Manufacturing
41,2020007786,PRIMAL COFFEE COMPANY,cd_2,311999,ALL OTHER MISCELLANEOUS FOOD MFG,6,311999,311999,311999,311999,All Other Miscellaneous Food Manufacturing
42,2020007786,PRIMAL COFFEE COMPANY,cd_2,311999,ALL OTHER MISCELLANEOUS FOOD MFG,6,311999,311999,311999,311999,All Other Miscellaneous Food Manufacturing
43,2020007786,PRIMAL COFFEE COMPANY,cd_2,311999,ALL OTHER MISCELLANEOUS FOOD MFG,6,311999,311999,311999,311999,All Other Miscellaneous Food Manufacturing
44,2020013537,MOTHER TO MOTHER MIDWIFERY,cd_3,621399,OFFICES OF ALL OTH MISC HEALTH PRACTITIONERS,6,621399,621399,621399,621399,Offices of All Other Miscellaneous Health Prac...
45,2020013537,MOTHER TO MOTHER MIDWIFERY,cd_3,621399,OFFICES OF ALL OTH MISC HEALTH PRACTITIONERS,6,621399,621399,621399,621399,Offices of All Other Miscellaneous Health Prac...
46,2021010826,STARDUST FLOAT SPA LP,cd_2,812199,OTHER PERSONAL CARE SERVICES,6,812199,812199,812199,812199,Other Personal Care Services
47,2003021665,SDDR V LP,cd_7,523999,MISCELLANEOUS FINANCIAL INVESTMENT ACTIVITIES,6,523999,523999,523999,523999,Miscellaneous Financial Investment Activities
48,2003021665,SDDR V LP,cd_7,523999,MISCELLANEOUS FINANCIAL INVESTMENT ACTIVITIES,6,523999,523999,523999,523999,Miscellaneous Financial Investment Activities
49,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,811198,811198,811198,All Other Automotive Repair and Maintenance
50,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,811198,811198,811198,All Other Automotive Repair and Maintenance
51,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,811198,811198,811198,All Other Automotive Repair and Maintenance

,account_key,dba_name,council_district,naics_code,naics_description_x,naics_nchar,new_naics_code,new_2_naics_code,new_second_naics_code,naics,naics_description_y,_merge
169,2018002456,CLARK BUILDERS LP,cd_1,233,"BUILDING, DEVELOPING & GENERAL CONTRACTING",3.0,233000,233000,233000.0,NaN,NaN,left_only
170,2016001854,DFS FLOORING LP,cd_5,23552,FLOOR LAYING & OTHER FLOOR CONTRACTORS,5.0,235520,235520,235520.0,NaN,NaN,left_only
171,2009034447,TRANSCORE LP,cd_6,23599,ALL OTHER SPECIAL TRADE CONTRACTORS,5.0,235990,235990,235990.0,NaN,NaN,left_only
327,2013048493,INTELLIGENT BLENDS,cd_1,31192,COFFEE & TEA MFG,5.0,311920,311920,311920.0,NaN,NaN,left_only
350,2016011401,PALI WINE COMPANY,cd_3,31213,WINERIES,5.0,312130,312130,312130.0,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...
2488,2020013274,IMPROVISED ELECTRONICS LLC,cd_8,81,OTHER BUSINESS SERVICES,2.0,810000,810000,810000.0,NaN,NaN,left_only
2511,2008000907,FIRE MASTER,cd_5,8113,COMMERCIAL EQUIPMENT (EXC AUTO & ELEC) R&M,4.0,811300,811300,811300.0,NaN,NaN,left_only
2532,2006012771,TATTOO ROYALE/TATTOO ROYALE INK,cd_2,812196,TATTOO PARLORS,6.0,812196,812196,812196.0,NaN,NaN,left_only
2548,2015022760,SHEWRY SALDA A LLP,cd_3,8129,OTHER PERSONAL SERVICES,4.0,812900,812900,812900.0,NaN,NaN,left_only
2552,2007029394,BORDER STATION PARKING,cd_8,81293,PARKING LOTS & GARAGES,5.0,812930,812930,812930.0,NaN,NaN,left_only

naics_nchar
6    52
Name: count, dtype: int64

## "Left join"- retain all sd businesses even if naics code isn't in `naics_df`

- Using the same join keys as above, and treating the San Diego businesses as the left hand side data, left join the naics code details onto the San Diego businesses
- Use the `indicator` argument within merge to create an indicator, `naics_merge_status`, to help with later merge diagnostics and examine sample of ones that didn't merge
- Use the `suffixes` argument within merge to add `_sd` as the left suffix, `_census` as the right suffix
- Use `naics_merge_status` in the merged result to look at a sample of San Diego businesses that weren't matched with `naics_df`

In [193]:
# your code here
left_join = pd.merge(sd_df, naics_df, left_on='naics_code', right_on='naics', how='left', indicator="naics_merge_status",
                    suffixes=["_sd", "_census"])
print(left_join.shape)
left_join
left_join.naics_merge_status.value_counts()
left_only = left_join[left_join['naics_merge_status'] == "left_only"]
print(left_only.shape)
print(naics_df.shape)

print("##### Class answer:")
merged_left = SD.merge(NA, left_on = 'naics_code', right_on = 'naics', how = 'left', indicator = True, suffixes = ['_sd', '_census'])
lost_data = merged_left[merged_left['_merge'] == 'left_only']
print(lost_data.head())

(370, 12)

,account_key,dba_name,council_district,naics_code,naics_description_sd,naics_nchar,new_naics_code,new_2_naics_code,new_second_naics_code,naics,naics_description_census,naics_merge_status
0,1974000448,ERNST & YOUNG LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants,both
1,1974011093,HECHT SOLBERG ROBINSON GOLDBERG & BAGLEY LLP,cd_3,5411,LEGAL SERVICES,4,541100,541100,541100,NaN,NaN,left_only
2,1978039819,RSM US LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants,both
3,1978042092,THORSNES BARTOLOTTA MCGUIRE LLP,cd_3,5411,LEGAL SERVICES,4,541100,541100,541100,NaN,NaN,left_only
4,1979046817,KORENIC & WOJDOWSKI LLP,cd_7,5412,ACCOUNTING/TAX PREP/BOOKKEEP/PAYROLL SERVICES,4,541200,541200,541200,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...
365,2010010820,ROSSLYN LOFTS HOUSING PARTNERS LP THE,cd_6,541,"PROFESSIONAL, SCIENTIFIC & TECHNICAL SERVICES",3,541000,541000,541000,NaN,NaN,left_only
366,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,811198,811198,811198,All Other Automotive Repair and Maintenance,both
367,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,811198,811198,811198,All Other Automotive Repair and Maintenance,both
368,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,811198,811198,811198,All Other Automotive Repair and Maintenance,both
369,2014014569,JLMR INVESTMENTS LP,cd_2,531,REAL ESTATE,3,531000,531000,531000,NaN,NaN,left_only

naics_merge_status
left_only     318
both           52
right_only      0
Name: count, dtype: int64

(318, 12)
(2270, 2)
##### Class answer:
  account_key                                      dba_name council_district  \
1  1974011093  HECHT SOLBERG ROBINSON GOLDBERG & BAGLEY LLP             cd_3
3  1978042092               THORSNES BARTOLOTTA MCGUIRE LLP             cd_3
4  1979046817                       KORENIC & WOJDOWSKI LLP             cd_7
5  1979053082    GRIMM VRANJES GREER STEPHAN & BRIDGMAN LLP             cd_3
6  1981000840                          BENINK & SLAVENS LLP             cd_7

  naics_code                           naics_description_sd  naics_nchar  \
1       5411                                 LEGAL SERVICES            4
3       5411                                 LEGAL SERVICES            4
4       5412  ACCOUNTING/TAX PREP/BOOKKEEP/PAYROLL SERVICES            4
5       5411                                 LEGAL SERVICES            4
6       5411                                 LEGAL SERVICES            4

  new_naics_code new_2_naics_code  new_second_naics_code naics  \
1         541100           541100                 541100   NaN
3         541100           541100                 541100   NaN
4         541200           541200                 541200   NaN
5         541100           541100                 541100   NaN
6         541100           541100                 541100   NaN

  naics_description_census     _merge
1                      NaN  left_only
3                      NaN  left_only
4                      NaN  left_only
5                      NaN  left_only
6                      NaN  left_only

In [197]:
left_join.naics_merge_status.value_counts(normalize=True) # This will give you proportions!

naics_merge_status
left_only     0.859459
both          0.140541
right_only    0.000000
Name: proportion, dtype: float64

## Use group by and agg to see if there are differences in merge rates by area

- Using the left-joined dataframe created in previous step, create a boolean indicator, `is_lost`, that equals `True` if the merge indicator is equal to "left_only" (and is otherwise false)
- Find the proportion of businesses by council district that were lost in the left join (SD businesses that failed to match to `naics_df`). To do this, group by `council_district` and use the shortcut of taking the mean of the `is_lost` indicator to find the proportions lost by `council_district`.

In [115]:
# your code here
left_join["is_lost"] = left_join["naics_merge_status"].apply(lambda x: x == "left_only")
left_join

# Find the proportion of businesses by council district that were lost in the left join (SD businesses that failed to match to naics_df). 
# To do this, group by council_district and use the shortcut of taking the mean of the is_lost indicator to find 
# the proportions lost by council_district.
left_join.groupby("council_district").agg({ "is_lost" : lambda x: x.mean()} )

,account_key,dba_name,council_district,naics_code,naics_description_sd,naics_nchar,new_naics_code,naics,naics_description_census,naics_merge_status,is_lost
0,1974000448,ERNST & YOUNG LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,Offices of Certified Public Accountants,both,False
1,1974011093,HECHT SOLBERG ROBINSON GOLDBERG & BAGLEY LLP,cd_3,5411,LEGAL SERVICES,4,541100,NaN,NaN,left_only,True
2,1978039819,RSM US LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,Offices of Certified Public Accountants,both,False
3,1978042092,THORSNES BARTOLOTTA MCGUIRE LLP,cd_3,5411,LEGAL SERVICES,4,541100,NaN,NaN,left_only,True
4,1979046817,KORENIC & WOJDOWSKI LLP,cd_7,5412,ACCOUNTING/TAX PREP/BOOKKEEP/PAYROLL SERVICES,4,541200,NaN,NaN,left_only,True
...,...,...,...,...,...,...,...,...,...,...,...
365,2010010820,ROSSLYN LOFTS HOUSING PARTNERS LP THE,cd_6,541,"PROFESSIONAL, SCIENTIFIC & TECHNICAL SERVICES",3,541000,NaN,NaN,left_only,True
366,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,811198,All Other Automotive Repair and Maintenance,both,False
367,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,811198,All Other Automotive Repair and Maintenance,both,False
368,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,811198,All Other Automotive Repair and Maintenance,both,False
369,2014014569,JLMR INVESTMENTS LP,cd_2,531,REAL ESTATE,3,531000,NaN,NaN,left_only,True

                   is_lost
council_district
cd_1              0.880597
cd_2              0.804348
cd_3              0.812500
cd_4              1.000000
cd_5              0.916667
cd_6              0.859649
cd_7              0.918919
cd_8              0.933333
cd_9              1.000000

In [ ]:
### Ming's solution 
#merged_left["is_lost"].astype(int).mean() # Find proportion

## Optional challenge exercise: add lagging 0's and see if merge rate improves

You noticed earlier that a big reason for non-matches is that the San Diego tax certificate NAICS codes were often less than six digits long, while the Census ones were always 6 digits.

You wonder if this is an issue where 0's in some of the SD's data naics codes got cut off (eg 540000 became 54), and if so whether adding these lagging zeros would improve the merge rate in a left join.

- Pad the `naics_code` column in `sd_df` with 0's to get that column up to 6-digits, using one of two approaches: 
  1. `str.pad` in pandas (https://pandas.pydata.org/docs/reference/api/pandas.Series.str.pad.html)
  2. for more of a challenge, write your own function! It should check the # of digits in the naics code string and pad it with 0's at the end up to 6 digits. To execute your function, use row-wise apply: `df.apply(lambda row: funcname(row.column), axis=1)`.
- Perform the same left join as above and see how the match rate changes
- Create an indicator variable--`is_new_match`---for new matches under the padded NAICS code; compare the `naics_description` column from San Diego versus Census in the new dataset for a sample of these new matches and comment on whether the padding seems to be correct

In [199]:
# Option 1 (use built-in function)
sd_df["new_naics_code"] = sd_df.naics_code.str.pad(width=6, side='right', fillchar='0') # Apply function 
sd_df.new_naics_code.apply(lambda x: len(x)).value_counts() # Verify 

# Merge 
left_join_2 = pd.merge(sd_df, naics_df, left_on='new_naics_code', right_on='naics', how='left', indicator="naics_merge_status",
                    suffixes=["_sd", "_census"]) 
print(left_join_2.shape)
left_join_2

# Checking that proportion of is_lost decreases 
left_join_2["is_lost"] = left_join_2["naics_merge_status"].apply(lambda x: x == "left_only")
left_join_2.groupby("council_district").agg({ "is_lost" : lambda x: x.mean()} )

# Option 2 (write a function challenge) 
# def padZeros(naics):
#     num_digits = len(naics)
#     if num_digits < 6: 
#         necessary_zeros = 6 - num_digits  
#         for i in range(necessary_zeros):
#             naics += "0"
#     return naics 

# Simplified function!!
def padZeros(naics):
    num_digits = len(naics)
    necessary_zeros = 6 - num_digits  
    return naics + "0" * necessary_zeros 

# Even more simplified line!
#pad_zeros = lambda x: "NAICS: "+ x + "0"*(6-len(x)) 

sd_df["new_2_naics_code"] = sd_df.apply(lambda row: padZeros(row.naics_code), axis=1) # Apply function 
left_join_3 = pd.merge(sd_df, naics_df, left_on='new_2_naics_code', right_on='naics', how='left', indicator="naics_merge_status",
                    suffixes=["_sd", "_census"])
print(left_join_3.shape)
left_join_3

# Last Step: Check the results of both functions with anti join, but there's no built-in function in pandas  
anti_join = left_join_3[~(left_join_3['new_2_naics_code'].isin(left_join_2['new_naics_code']) & left_join_3['naics'].isin(left_join_2['naics']))]

print(anti_join.shape)
print(anti_join.shape[0] == 0) # Should be True

new_naics_code
6    353
Name: count, dtype: int64

(446, 12)

,account_key,dba_name,council_district,naics_code,naics_description_sd,naics_nchar,new_naics_code,new_2_naics_code,new_second_naics_code,naics,naics_description_census,naics_merge_status
0,1974000448,ERNST & YOUNG LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants,both
1,1974011093,HECHT SOLBERG ROBINSON GOLDBERG & BAGLEY LLP,cd_3,5411,LEGAL SERVICES,4,541100,541100,541100,NaN,NaN,left_only
2,1978039819,RSM US LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants,both
3,1978042092,THORSNES BARTOLOTTA MCGUIRE LLP,cd_3,5411,LEGAL SERVICES,4,541100,541100,541100,NaN,NaN,left_only
4,1979046817,KORENIC & WOJDOWSKI LLP,cd_7,5412,ACCOUNTING/TAX PREP/BOOKKEEP/PAYROLL SERVICES,4,541200,541200,541200,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...
441,2010010820,ROSSLYN LOFTS HOUSING PARTNERS LP THE,cd_6,541,"PROFESSIONAL, SCIENTIFIC & TECHNICAL SERVICES",3,541000,541000,541000,NaN,NaN,left_only
442,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,811198,811198,811198,All Other Automotive Repair and Maintenance,both
443,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,811198,811198,811198,All Other Automotive Repair and Maintenance,both
444,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,811198,811198,811198,All Other Automotive Repair and Maintenance,both
445,2014014569,JLMR INVESTMENTS LP,cd_2,531,REAL ESTATE,3,531000,531000,531000,NaN,NaN,left_only

                   is_lost
council_district
cd_1              0.546667
cd_2              0.555556
cd_3              0.348148
cd_4              1.000000
cd_5              0.483871
cd_6              0.445946
cd_7              0.560976
cd_8              0.333333
cd_9              1.000000

(446, 12)

,account_key,dba_name,council_district,naics_code,naics_description_sd,naics_nchar,new_naics_code,new_2_naics_code,new_second_naics_code,naics,naics_description_census,naics_merge_status
0,1974000448,ERNST & YOUNG LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants,both
1,1974011093,HECHT SOLBERG ROBINSON GOLDBERG & BAGLEY LLP,cd_3,5411,LEGAL SERVICES,4,541100,541100,541100,NaN,NaN,left_only
2,1978039819,RSM US LLP,cd_1,541211,OFFICES OF CERTIFIED PUBLIC ACCOUNTANTS,6,541211,541211,541211,541211,Offices of Certified Public Accountants,both
3,1978042092,THORSNES BARTOLOTTA MCGUIRE LLP,cd_3,5411,LEGAL SERVICES,4,541100,541100,541100,NaN,NaN,left_only
4,1979046817,KORENIC & WOJDOWSKI LLP,cd_7,5412,ACCOUNTING/TAX PREP/BOOKKEEP/PAYROLL SERVICES,4,541200,541200,541200,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...
441,2010010820,ROSSLYN LOFTS HOUSING PARTNERS LP THE,cd_6,541,"PROFESSIONAL, SCIENTIFIC & TECHNICAL SERVICES",3,541000,541000,541000,NaN,NaN,left_only
442,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,811198,811198,811198,All Other Automotive Repair and Maintenance,both
443,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,811198,811198,811198,All Other Automotive Repair and Maintenance,both
444,2014004525,INSTANT SMOG CHECK,cd_6,811198,ALL OTHER AUTOMOTIVE R&M,6,811198,811198,811198,811198,All Other Automotive Repair and Maintenance,both
445,2014014569,JLMR INVESTMENTS LP,cd_2,531,REAL ESTATE,3,531000,531000,531000,NaN,NaN,left_only

(0, 12)
True